### ISSUE TITLE
Do you want me to work on improving the UI?

### ISSUE THREAD

**Issue by imsahiljain** [Aleksit0/Blog#6]

**Comment by Aleksit0** [comment]
Sure! Push your commits on test branch.

**Comment by Aleksit0** [comment]
> _No description provided._

Please, keep it simple and modern.

**Comment by VirajS00** [comment]
Can I contribute to this?

**Comment by Aleksit0** [comment]
> Can I contribute to this?

Sure, what will you do?

**Comment by VirajS00** [comment]
I want to improve the UI for the section showing the blog posts

> > Can I contribute to this?
> 
> Sure, what will you do?

**Comment by Aleksit0** [comment]
> I want to improve the UI for the section showing the blog posts
> 
> > > Can I contribute to this?
> > 
> > 
> > Sure, what will you do?

Great

**Comment by Aleksit0** [comment]
I recommend you to finish the work by tonight, if you are not able to it for tonight, please do it until Tuesday. Thank you !

**Comment by imsahiljain** [comment]
issued a PR #7 for improvement of UI

**Comment by Aleksit0** [comment]
> issued a PR #7 for improvement of UI

Great.

**Comment by imsahiljain** [comment]
> > issued a PR #7 for improvement of UI
> 
> Great. PS For some reason your PR does not count on my hacktoberfest status page.

Might appear in some time. Refresh it.

**Comment by Aleksit0** [comment]
> > > issued a PR #7 for improvement of UI
> > 
> > 
> > Great. PS For some reason your PR does not count on my hacktoberfest status page.
> 
> Might appear in some time. Refresh it.

My bad. I think it only counts for you since you made a PR to my repo. I am the maintainer and I only merge and accept them.

**Comment by imsahiljain** [comment]
ok

**Comment by Aleksit0** [comment]
> ok

Can you please screenshot the design you made?

**Comment by imsahiljain** [comment]
I could if my screen would not change it's color to pink. 
You may just checkout to test branch using `git checkout test` and see the `index.html` file.

**Comment by imsahiljain** [comment]
![image](https://user-images.githubusercontent.com/63599413/135718073-a2463ac6-7034-4bdf-95fb-78450c3a7f5a.png)

**Comment by imsahiljain** [comment]
My screen's color somehow changed to pink...

**Comment by VirajS00** [comment]
You can also pull the test branch using `git pull origin test` to pull it locally.

**Comment by Aleksit0** [comment]
Design is AWESOME, great job !

**Comment by imsahiljain** [comment]
> Design is AWESOME, great job !

Thanks, could do more better, but due to some problem I couldn't see the colors correctly.

**Comment by Aleksit0** [comment]
> > Design is AWESOME, great job !
> 
> Thanks, could do more better, but due to some problem I couldn't see the colors correctly.

It's awesome, I'm satisfied !

**Comment by Aleksit0** [comment]
I want to thank you for taking your time to contribute to my project. Also, I would appreciate if you could follow me and star some of my projects. Great work and thank you !

**Comment by Aleksit0** [comment]
Does anyone know any free site hosts other than netlify?

**Comment by VirajS00** [comment]
> Does anyone know any free site hosts other than netlify?

You could checkout github pages and cloudflare pages too (they're very similar to netlify) and heroku (freemium) if you want to host full stack apps

**Comment by Aleksit0** [comment]
I'll check them out.
