### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by VirajS00** [Aleksit0/Blog#9]
The website is currently breaking when I resize the browser window.  

<img width="485" alt="Screenshot 2021-10-02 at 11 48 59 PM" src="https://user-images.githubusercontent.com/72297793/135727707-9b3817bf-f150-48be-ad9c-1d5b65ab8296.png">

**Comment by VirajS00** [comment]
Can I work on this?

**Comment by Aleksit0** [comment]
Sure

**Comment by VirajS00** [comment]
I made a PR for this, you can review it

**Comment by Aleksit0** [comment]
I'll review it now.

**Comment by SarthakGautam2561** [comment]
Hello, Can anyone assign me any task for hacktoberfest?

**Comment by SarthakGautam2561** [comment]
only Related to web development

**Comment by Aleksit0** [comment]
There are some things that you didn't have to change in index.html file or that are considered spam. In style.css I saw some responsive improvements. Next time you make a change focus on a functionality rather than changing spaces somewhere 👍🏼 .
Overall GREAT JOB !

**Comment by Aleksit0** [comment]
> Hello, Can anyone assign me any task for hacktoberfest?

Hello, what would you do?

**Comment by SarthakGautam2561** [comment]
> > Hello, Can anyone assign me any task for hacktoberfest?
> 
> Hello, what would you do?

Anything in web development from html, css and javascript.

**Comment by Aleksit0** [comment]
> > > Hello, Can anyone assign me any task for hacktoberfest?
> > 
> > 
> > Hello, what would you do?
> 
> Anything in web development from html, css and javascript.

I saw some of your projects. Since you are a beginner, you should do some simple animations in js (animations when we laod the site). Do you know Git well?

**Comment by SarthakGautam2561** [comment]
Yes I can make a pull request.

**Comment by SarthakGautam2561** [comment]
Should I start making the animation?

**Comment by Aleksit0** [comment]
> Should I start making the animation?

Yes, keep it simple.

**Comment by SarthakGautam2561** [comment]
> > Should I start making the animation?
> 
> Yes, keep it simple.

I have made a PR for the preloader you can review it now.

**Comment by SarthakGautam2561** [comment]
And in index.html there are many additions and deletions actually my code beautifier made those changes by beautifying the code so just ignore them. I have done everything right you can check yourself by copying code from my forked repository.

**Comment by Aleksit0** [comment]
> > > Should I start making the animation?
> > 
> > 
> > Yes, keep it simple.
> 
> I have made a PR for the preloader you can review it now.

Alright.

**Comment by Aleksit0** [comment]
*Due to time-zone difference between you and me, I'm not able to respond to every issue quickly. I will do my best to respond to you and your PRs as soon as I can. Thank you.

**Comment by SarthakGautam2561** [comment]
it's okay buddy. I understand.

**Comment by Aleksit0** [comment]
Did you use "test" branch ?

**Comment by SarthakGautam2561** [comment]
No. I don't even know what it is.

**Comment by SarthakGautam2561** [comment]
Okay I got it. I can do the same in test branch if you want.

**Comment by Aleksit0** [comment]
> No. I don't even know what it is.

Ok, don't worry. Look at this video to learn what are branches: https://www.youtube.com/watch?v=oPpnCh7InLY

**Comment by Aleksit0** [comment]
> Okay I got it. I can do the same in test branch if you want.

Since we do everything on a "test" branch, you can do it on there.

**Comment by SarthakGautam2561** [comment]
Bro please add a label of "hacktoberfest-accepted" to my PR otherwise it will not be counted.

**Comment by SarthakGautam2561** [comment]
Okay I will do it.

**Comment by Aleksit0** [comment]
I've sent you guys an invitation to my Github organization. It is a great place where we can build projects and grow as a developers together. I would appreciate it if you accept the invitation. Thank you.

**Comment by SarthakGautam2561** [comment]
okay I will join.

**Comment by Aleksit0** [comment]
Thank you !

**Comment by SarthakGautam2561** [comment]
I have joined the organization and also made the PR in test branch.

**Comment by Aleksit0** [comment]
Since this is a open-source repository, you don't need to fork it to your profile. Git pull-ing it to your local machine will be better.
Also, forking it to your profile will decrease the chances of me and you getting valid PRs for Hacktoberfest, thus lowering the chances of us getting the prizes.

**Comment by SarthakGautam2561** [comment]
Actually I don't know how to use the terminal. I will learn it this month. I am 14 years old

**Comment by SarthakGautam2561** [comment]
Good Night :) Time to sleep in my country.

**Comment by Aleksit0** [comment]
Good night, tomorrow you can git clone this project to your pc. It's better for the reasons I mentioned here: https://github.com/Aleksit0/Blog/issues/9#issuecomment-932985973

**Comment by SarthakGautam2561** [comment]
Okay Bro.

**Comment by Aleksit0** [comment]
Overall you did a great job. Good night !

**Comment by SarthakGautam2561** [comment]
:)

**Comment by SarthakGautam2561** [comment]
Now what should I do next?

**Comment by Aleksit0** [comment]
Now, you can rest until I come up with a new idea for this project. My suggestion for you is to learn Git and improve your skills in html/css/js while you are not working on this.

**Comment by Aleksit0** [comment]
@VirajS00 Can you work on the dark theme for the blog?

**Comment by SarthakGautam2561** [comment]
Yes, I can but from tomorrow!

**Comment by Aleksit0** [comment]
> Yes, I can but from tomorrow!

No need for !. I asked Viraj to do it since he is a more experienced developer. PS As a beginner you did a very good job!

**Comment by SarthakGautam2561** [comment]
Oh okay!

**Comment by SarthakGautam2561** [comment]
You can Tell me if there is anything I can do.

**Comment by Aleksit0** [comment]
Sure. When I come up with some new ideas, I will let you guys know. Until then, focus on improving your skills, you are young and it will help you A LOT!

**Comment by VirajS00** [comment]
> @VirajS00 Can you work on the dark theme for the blog?

Yeah sure, just that I can only start working on that by evening today

**Comment by VirajS00** [comment]
> Now what should I do next?

Maybe find another project to contribute to 😄, look for the `good first issue` tag

**Comment by Aleksit0** [comment]
> > @VirajS00 Can you work on the dark theme for the blog?
> 
> Yeah sure, just that I can only start working on that by evening today 

Okay, no problem.

**Comment by VirajS00** [comment]
@Aleksit0 just made a pull request for darkmode

**Comment by Aleksit0** [comment]
Alright, I'll review it in a minute.

**Comment by Aleksit0** [comment]
Once again, I want you not to fork this repository to your profile. Instead, git clone it to your local computer. This way, we both get valid Hacktoberfest 2021 PR's. If you fork it, the PR's only count for you. As a maintainer, I don't get PR's that you have submitted on my Hacktoberfest 2021 progress page. Thank you!

**Comment by Aleksit0** [comment]
> @Aleksit0 just made a pull request for darkmode

It's awesome, great job! There is a bit work to do on responsivnes. If you could do that please let me know.

**Comment by SarthakGautam2561** [comment]
Hey, I think I can work on responsiveness. I am starting working now and will made a pr soon

**Comment by VirajS00** [comment]
> > @Aleksit0 just made a pull request for darkmode
> 
> It's awesome, great job! There is a bit work to do on responsivnes. If you could do that please let me know.

Lets give someone else a chance to work on that

**Comment by Aleksit0** [comment]
> > > @Aleksit0 just made a pull request for darkmode
> > 
> > 
> > It's awesome, great job! There is a bit work to do on responsivnes. If you could do that please let me know.
> 
> Lets give someone else a chance to work on that

Good idea. This could be possible if you could star the project so more people doing hacktoberfest can reach us and help us out. 
I will tag a guy who asked to work on this project to finish this. Thank you!

**Comment by VirajS00** [comment]
> Once again, I want you not to fork this repository to your profile. Instead, git clone it to your local computer. This way, we both get valid Hacktoberfest 2021 PR's. If you fork it, the PR's only count for you. As a maintainer, I don't get PR's that you have submitted on my Hacktoberfest 2021 progress page. Thank you!

I think if you add the `hacktoberfest-accepted` label before merging the PR, it should count towards hacktoberfest for you

**Comment by Aleksit0** [comment]
> > Once again, I want you not to fork this repository to your profile. Instead, git clone it to your local computer. This way, we both get valid Hacktoberfest 2021 PR's. If you fork it, the PR's only count for you. As a maintainer, I don't get PR's that you have submitted on my Hacktoberfest 2021 progress page. Thank you!
> 
> I think if you add the `hacktoberfest-accepted` label before merging the PR, it should count towards hacktoberfest for you

I'll consider doing that in the future. I tested this some time ago and it turns out that PRs from git cloned repo count (PRs without hacktoberfest label). I already have 4+ valid PRs so this subject is only for discussion. Note that this is my first time as a maintainer in Hacktoberfest and there is a lot of material to learn. Thank you!

**Comment by VirajS00** [comment]
I'm not a maintainer but I made a PR to another repo and they added the label before merging it

**Comment by Aleksit0** [comment]
> I'm not a maintainer but I made a PR to another repo and they added the label before merging it 

I know that you are not a maintainer, but the things are different since I am one. There is no big difference in adding a label or not. The main difference is in the way you aquire the repo and merge PRs (as a maintainer). With this said, we are done on this subject.

Also, I'm closing this issue as of today. I'll make a new issue to make things more organized and easier to interact.

Sincerely,
Aleksa
